version: '3.7'

services:
  oathkeeper:
    container_name: oathkeeper  
    image: oryd/oathkeeper:v0.38
    depends_on:
      - kratos
    ports:
      - 8001:4455
      - 4456:4456
    command: serve proxy -c "/etc/config/oathkeeper/oathkeeper.yml"
    environment:
      - LOG_LEVEL=debug
    restart: on-failure
    networks:
      - intranet
    volumes:
      - ./oathkeeper:/etc/config/oathkeeper

  fastapi:
    container_name: fastapi  
    build:
      context: .
    image: fastapi_app
    environment:
      - ENV=development
    ports:
      - "8000:8000"
    networks:
      - intranet
    restart: on-failure
    volumes:
      - .:/app

  postgres:
    container_name: postgres
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=local
    networks:
      - intranet

  kratos-migrate:
    container_name: kratos-migrate  
    image: oryd/kratos:v0.8.0-alpha.3
    depends_on:
      - postgres
    environment:
      - DSN=postgres://postgres:password@postgres:5432/local?sslmode=disable&max_conns=20&max_idle_conns=4
    networks:
      - intranet
    volumes:
      - ./kratos:/etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes

  kratos:
    container_name: kratos  
    image: oryd/kratos:v0.8.0-alpha.3
    depends_on:
      - postgres
    environment:
      - DSN=postgres://postgres:password@postgres:5432/local?sslmode=disable&max_conns=20&max_idle_conns=4
    ports:
      - "4433:4433"
      - "4434:4434"
    networks:
      - intranet
    volumes:
      - ./kratos:/etc/config/kratos
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier

  # kratos-selfservice-ui-node:
  #   image: oryd/kratos-selfservice-ui-node:v0.8.0-alpha.3
  #   environment:
  #     - KRATOS_PUBLIC_URL=http://kratos:4433/
  #     - KRATOS_BROWSER_URL=http://127.0.0.1:4433/
  #   networks:
  #     - intranet
  #   ports:
  #     - "3000:3000"
  #   restart: on-failure

  mailslurper:
    container_name: mailslurper 
    image: oryd/mailslurper:latest-smtps
    ports:
      - "4436:4436"
      - "4437:4437"
    networks:
      - intranet

  # postgres-keto:
  #   image: postgres:9.6
  #   ports:
  #     - "15432:5432"
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_DB=keto
  #   networks:
  #     - intranet

  keto-migrate:
    container_name: keto-migrate 
    image: oryd/keto:v0.7.0-alpha.1
    volumes:
      - ./keto:/home/ory
    environment:
      - LOG_LEVEL=debug
      - DSN=postgres://postgres:password@postgres:5432/local?sslmode=disable&max_conns=20&max_idle_conns=4
    command: ["migrate", "up", "-y"]
    restart: on-failure
    depends_on:
      - postgres
    networks:
      - intranet

  keto:
    container_name: keto  
    image: oryd/keto:v0.7.0-alpha.1
    volumes:
      - ./keto:/home/ory
    ports:
      - "4466:4466"
      - "4467:4467"
    depends_on:
      - keto-migrate
    environment:
      - DSN=postgres://postgres:password@postgres:5432/local?sslmode=disable&max_conns=20&max_idle_conns=4
    networks:
      - intranet
    command: serve

networks:
  intranet:
